### ISSUE TITLE
When joining a room with example: ArgumentError: wrong number of arguments (given 0, expected 1)

### ISSUE THREAD

**Issue by Preen** [palkan/litecable#1]
`bundle exec puma`

127.0.0.1 - - [03/Feb/2017:14:18:47 +0100] "POST /sign_in HTTP/1.1" 303 - 0.0009
127.0.0.1 - - [03/Feb/2017:14:18:47 +0100] "GET / HTTP/1.1" 200 631 0.0089
127.0.0.1 - - [03/Feb/2017:14:18:51 +0100] "POST /rooms HTTP/1.1" 303 - 0.0006
127.0.0.1 - - [03/Feb/2017:14:18:51 +0100] "GET /rooms/1 HTTP/1.1" 200 2367 0.0096
2017-02-03 14:18:51 +0100: Rack app error handling request { GET /cable }
#<ArgumentError: wrong number of arguments (given 0, expected 1)>
/Users/philipmannheimer/Documents/flewid/testing-environments/litecable/lib/lite_cable/server/websocket_ext/protocols.rb:7:in `protocols'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/websocket-1.2.4/lib/websocket/handshake/handler/server04.rb:48:in `protocol'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/websocket-1.2.4/lib/websocket/handshake/handler/server04.rb:26:in `handshake_keys'
/Users/philipmannheimer/Documents/flewid/testing-environments/litecable/lib/lite_cable/server/websocket_ext/protocols.rb:27:in `handshake_keys'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/websocket-1.2.4/lib/websocket/handshake/handler/base.rb:13:in `to_s'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/websocket-1.2.4/lib/websocket/handshake/base.rb:31:in `to_s'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/websocket-1.2.4/lib/websocket/exception_handler.rb:19:in `block in rescue_method'
/Users/philipmannheimer/Documents/flewid/testing-environments/litecable/lib/lite_cable/server/middleware.rb:37:in `send_handshake'
/Users/philipmannheimer/Documents/flewid/testing-environments/litecable/lib/lite_cable/server/middleware.rb:21:in `call'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:66:in `block in call'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `each'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `call'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:153:in `call'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/configuration.rb:226:in `call'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:578:in `handle_request'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:415:in `process_client'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:275:in `block in run'
/Users/philipmannheimer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by palkan** [comment]
That was caused by the recent update of [websocket-ruby](https://github.com/imanel/websocket-ruby) (just the day after I've released the gem). Now it supports subprotocols, thus conflicting with my own implementation (I'm getting rid of it).
