### ISSUE TITLE
LiteCable::Server::ClientSocket::Base doesn't have a attr reader for env even though it's needed

### ISSUE THREAD

**Issue by Thermatix** [palkan/litecable#52]
I'm building some specs by using the same technique that is used in litecable. (spinning up a Puma server to run WS requests against) I'm now at the point where the server is responding.
The issue is that, doing `request.params` causes an error:

```sh
Failure/Error: @request ||= Rack::Request.new(socket.env)

     NoMethodError:
       undefined method `env' for #<LiteCable::Server::ClientSocket::Base:0x00007ffe4ff89238>
       Did you mean?  end
```

The only way to fix it is to monkey patch it in:

```ruby
module LiteCable
  module Server
    module ClientSocket
      # Wrapper over web socket
      class Base
        def env
          @env
        end
      end
    end
  end
end
```

**Comment by palkan** [comment]
> `@request ||= Rack::Request.new(socket.env)` 

Where is this code from? 
You can access `env` via `socket.request.env` (`socket.request` is actually `Rack::Request.new(@env)`).

**Comment by Thermatix** [comment]
According to the backtrace `anycable.rb#L34`:
https://github.com/palkan/litecable/blob/a8c81dc654ffa5c10e9e3d3905a97e11218501be/lib/lite_cable/anycable.rb#L34

**Comment by palkan** [comment]
Your original error shows that you're using Puma (and `socket` is `LiteCable::Server::ClientSocket::Base` ).

In that case, you shouldn't enable AnyCable integration (which is enabled since you hit the `lite_cable/anycable.rb`).

**Comment by Thermatix** [comment]
The error occurs in my specs which I'm building using the technique in litecables own specs by using the [sync_client.rb][0] and then spinning up a puma server to bounce socket requests off of:

https://github.com/palkan/litecable/blob/a8c81dc654ffa5c10e9e3d3905a97e11218501be/spec/integrations/server_spec.rb#L55-L65

As for the anycable thing, we have the anycable gem as we're intending to use anycable-go in production but I'm doing:

```ruby
  require 'puma'
  require 'lite_cable/server'
```

[0]: https://github.com/palkan/litecable/blob/master/spec/support/sync_client.rb
