### ISSUE TITLE
`Errno::ECONNRESET: Connection reset by peer` should get caught

### ISSUE THREAD

**Issue by PeterLaudel** [palkan/litecable#67]
### Tell us about your environment

**Ruby version:**

2.7.0

**`litecable` gem version:**

0.7.0

**`anycable` gem version:**

**`grpc` gem version:**

### What did you do?
Running lite cable with a lot of connection

### What did you expect to happen?

Close the socket on receive `Errno::ECONNRESET: Connection reset by peer` [here](https://github.com/palkan/litecable/blob/d867e48ca4f36c5e8065f5ab8fd409452eb9358a/lib/lite_cable/server/client_socket/base.rb#L39) and do not let crash the whole application.

### What actually happened?

Whole application crashed.

**Comment by palkan** [comment]
Thanks for reporting! Fixed and released in 0.7.1.

**Comment by PeterLaudel** [comment]
Wow that was fast! Thanky you.
